# Generated by nixos-generate-config during installation.
# When installing:
#   1. Boot the NixOS installer ISO
#   2. Partition and mount disks at /mnt
#   3. Run: nixos-generate-config --root /mnt
#   4. Copy the result here:
#        cp /mnt/etc/nixos/hardware-configuration.nix hosts/alex-pc/hardware-configuration.nix
#   5. Commit and install with: nixos-install --flake .#alex-pc

{ ... }: { }
